# Generated by Django 3.0.4 on 2020-03-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plato', '0002_auto_20200316_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='precio',
            field=models.CharField(default='', max_length=20),
        ),
    ]
